services:
  app_vet:
    build: clinicavet
    ports:
      - "9475:9475"
    environment:
      DB_URL: jdbc:mysql://clinica_vet:3306/clinica_veterinaria?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      clinica_vet:
          condition: service_healthy


